### ISSUE TITLE
Transparent background with Chrome 94

### ISSUE THREAD

**Issue by wangenau** [nglviewer/ngl#884] opened 2021-09-25 10:31 UTC
Hello,
it seems that the recent Chrome update broke ngl for me. After updating to Chrome 94, content *behind* the interactive view will show through the viewer. I have attached a screenshot to show the issue.
The issue also exists in nglview. Setting a different background color did not help. Downgrading to an older Chrome/Chromium version would be a temporary fix.

ngl 2.0.0-dev.37
Chrome 94.0.4606.61

* Screenshot
![Screenshot from 2021-09-25 12-22-34](https://user-images.githubusercontent.com/15988797/134768302-ca7f433e-de92-4de2-9066-954782450b33.png)

**Comment by krassowski** [comment] 2021-09-29 21:35
I see this on Chrome 94 too (from time to time) using NVIDIA 470 drivers and X.org server.

**Comment by fredludlow** [comment] 2021-12-06 16:53
Is this still causing problems? (I haven't been able to reproduce it, but it sounds very driver/system specific...)

**Comment by wangenau** [comment] 2021-12-13 15:45
Yes, the issue still exists for me. The latest Chrome version 96.0.4664.93 still has this problem. Using an older Chrome version fixes the problem.
Firefox also does not has this bug, which makes this problem pretty bearable.
Maybe it has something to do with my OS (Ubuntu 16.04) and not only with Chrome.

**Comment by michaelidis** [comment] 2022-09-16 11:19
Any progress with this issue?

**Comment by fredludlow** [comment] 2022-09-16 11:38
Are there any errors in the console/debug tools? Google turns up a load of possibilities but without anything else to go on or way to reproduce I'm kind of stuck. If you're having trouble can you post:

* OS version
* Chrome version
* GPU make/model etc
* Graphics Drivers and system
* NGL version

Hopefully with a few replies it'll become a bit more obvious what the common factor is...

Negative data points: I've never seen this on windows 10 (Nvidia or Intel graphics) or Ubuntu 18.04 box (Intel graphics only, Xorg),

**Comment by michaelidis** [comment] 2022-09-16 11:48
![image](https://user-images.githubusercontent.com/77273826/190631347-a6327ca2-e6db-4f6f-96b5-9e980536eec3.png)

![image](https://user-images.githubusercontent.com/77273826/190631811-6b2d09da-fcf7-4b01-8672-423a4a6f9555.png)

Does this help any?

I am on ubuntu 22.04,  Chrome version is  105.0.5195.125 (Official Build) (64-bit),  does this help?
I don't think it is my GPU because I know from my colleagues they all see the problem using  Ubuntu/Chrome

**Comment by michaelidis** [comment] 2022-09-16 11:49
NGL version  ngl-ui.jsx: NGL.Version=2.0.0-dev.37

**Comment by michaelidis** [comment] 2022-09-16 13:19
Actually, just found the solution that works for me:
https://askubuntu.com/questions/299345/how-to-enable-webgl-in-chrome-on-ubuntu

**Comment by fredludlow** [comment] 2022-09-16 13:46
> Actually, just found the solution that works for me: https://askubuntu.com/questions/299345/how-to-enable-webgl-in-chrome-on-ubuntu

There's a lot going on on that link - was it the accepted answer that fixed it for you? ("Override software rendering list" and  "Use hardware acceleration when available")

**Comment by michaelidis** [comment] 2022-09-16 13:53
Yes that's the one.  Sorry about the fuss. It may be well that this may close this issue.

**Comment by fredludlow** [comment] 2022-09-18 20:44
Thanks for confirming! I'll close this for now.

**Closed by fredludlow** 2022-09-18 20:44 UTC
